name: khmer_fingerspelling_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages
publish_to: "none"

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# `flutter pub upgrade --major-versions`
# `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/KantumruyPro/KantumruyPro-Thin.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-ExtraLight.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-Light.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-Regular.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-Medium.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-SemiBold.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-Bold.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-ThinItalic.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-ExtraLightItalic.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-LightItalic.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-Italic.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-MediumItalic.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-SemiBoldItalic.ttf
        - asset: assets/fonts/KantumruyPro/KantumruyPro-BoldItalic.ttf

  # see https://flutter.dev/custom-fonts/#from-packages
